version: "3"
services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "9002:9002"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ${PWD}/acme.json:/etc/traefik/acme/acme.json
  microservice:
    build: .
    expose:
      - 9002