[log]
level = "DEBUG"

[entryPoints]

    [entryPoints.web]
    address = ":80"

    [entryPoints.web-secure]
    address = ":443"

[http]

    [http.routers]

        [http.routers.api]
        rule = "Method(`GET`)"
        middlewares = []
        entryPoints = [
            "web"
        ]
        service = "whoami"

    [http.services]

        [http.services.whoami]

            [http.services.whoami.loadBalancer]

                [[http.services.whoami.loadBalancer.servers]]
                url = "http://whoami:80"

[providers]
    [providers.file]
    filename = "/etc/traefik/traefik.toml"
    watch = true